
server:
  port: 8088
  servlet:
    context-path: "/student"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 2000
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    properties:
      hibernate:
        format-sql: true
  liquibase:
    enabled: true


